---


batch_size: 12000 # batch size to use by the clients
input_size: 7 # input size of the model
hidden_size: 16 # hidden size of the model
output_size: 2 # output size of the model
learning_rate: 0.001 # learning rate to use by the clients
local_epochs: 1 # number of training epochs each clients does in a fit() round
server_address: "127.0.0.1:8080" # address of the server